# Generated by Django 3.0.4 on 2020-03-11 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20200311_1023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site_slug',
            old_name='slug',
            new_name='name',
        ),
    ]
