# Generated by Django 3.0.4 on 2020-04-10 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_searchcheckmate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchcheckmate',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='searchcheckmate',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='searchcheckmate',
            name='title',
        ),
        migrations.AddField(
            model_name='searchcheckmate',
            name='json',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
