# Generated by Django 3.0.4 on 2020-04-10 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_auto_20200410_1631'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchCheckmate',
        ),
    ]
