# Generated by Django 3.0.4 on 2020-03-11 15:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_auto_20200311_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.UUIDField(default=uuid.UUID('60f99d8d-3ca5-4671-a6fa-bfb01471e267'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b3f6b077-3092-456a-b31b-0baa7cfd2947'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
