# Generated by Django 3.0.4 on 2020-03-11 16:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_auto_20200311_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.UUIDField(default=uuid.UUID('59b2f28e-7d77-4439-9e01-da656898546a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0dced39a-c4c3-4fe4-aa79-bb7ffee844f9'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
