# Generated by Django 3.0.4 on 2020-03-11 16:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_auto_20200311_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('62c33b63-05e8-48cb-b716-15a63f27fe29'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
