# Generated by Django 3.0.4 on 2020-03-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_auto_20200311_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site_slug',
            name='name',
            field=models.CharField(max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
