# Generated by Django 3.0.4 on 2020-03-11 19:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_auto_20200311_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d5dfb153-9480-4137-b233-179707fe9782'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f3763065-d73a-4a76-b039-aff0f8bea7c1'), editable=False, primary_key=True, serialize=False),
        ),
    ]
