# Generated by Django 3.0.4 on 2020-03-11 19:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_auto_20200311_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bf4e0e43-65bc-4a8f-83fe-6e2141ef3746'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8b0a40b7-4d4e-4487-b6bc-ab233fffe662'), editable=False, primary_key=True, serialize=False),
        ),
    ]
