# Generated by Django 3.0.4 on 2020-03-11 19:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_auto_20200311_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e1d02ffc-6876-43c6-8632-03ba97a08960'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6625b396-095e-4b28-a600-c5f28ec3bb30'), editable=False, primary_key=True, serialize=False),
        ),
    ]
