# Generated by Django 3.0.4 on 2020-04-03 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0015_auto_20200327_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='queries',
        ),
        migrations.CreateModel(
            name='QueryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('querynum', models.IntegerField(default=0)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.User')),
            ],
        ),
    ]
