# Generated by Django 3.0.4 on 2020-04-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0016_auto_20200403_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='site_slug',
            name='site_name',
            field=models.CharField(default='you should probably have filled this out instead of seeing this', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='queries',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
