# Generated by Django 3.0.2 on 2020-04-09 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0016_auto_20200403_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='queries',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='QueryInfo',
        ),
    ]
