# Generated by Django 3.0.2 on 2020-01-31 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('ISBN', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('publisher', models.CharField(max_length=200)),
                ('release_date', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=50)),
                ('series', models.CharField(max_length=200)),
                ('volume_number', models.CharField(max_length=10)),
            ],
        ),
    ]
