# Generated by Django 3.0.2 on 2020-02-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
