# Generated by Django 3.0.2 on 2020-02-10 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_bookstore', '0002_auto_20200210_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='f',
            field=models.FileField(upload_to=''),
        ),
    ]
