# Generated by Django 3.0.2 on 2020-02-10 22:39

from django.db import migrations, models
import test_bookstore.models


class Migration(migrations.Migration):

    dependencies = [
        ('test_bookstore', '0003_auto_20200210_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='f',
            field=models.FileField(upload_to=test_bookstore.models.user_directory_path),
        ),
    ]
